### PR TITLE
Made it all Reactive and stuff.

### PR DESCRIPTION
**Pull request by ashfurrow**

### CODE REVIEW

**Comment by tapi** [comment]
Oh god, why is the Pods directory in the repo?
;)

**Comment by ashfurrow** [comment]
Don't be snarky!

**Comment by tapi** [comment]
I've been using this as my .gitignore https://gist.github.com/tapi/5321825
works real well.

Commiting the Pods removes part of the advantage of using them, ie you have to manage/merge/deal with them.

Change looks good though.

**Comment by ashfurrow** [comment]
@tapi Yeah good point. I've updated the thingy.

**Comment by tapi** [comment]
Gorgeous, 23 files is much nicer than 301 ;)

**Comment by ashfurrow** [comment]
:bowtie:

**Pull request merged**
